wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1662036270.923548
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 13
      - 16
      - 23
      4: 3.8.13
      5: 0.13.2
      8:
      - 1
      - 5
epochs:
  desc: null
  value: 200
model:
  desc: null
  value: resnet34
optim:
  desc: null
  value: sgd
seed:
  desc: null
  value: 123
wandb_project:
  desc: null
  value: optimizer-evaluation
